config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'trash/view'

  get 'tags/index'

  get 'tags/show'

  get 'dashboard/show'
  get 'tags/:tag', to: 'tags#show'
  resources :notes
  resources :tags, only: [:index, :show]
  resources :notes do
    member do
      put 'share'
    end
  end
  
  resources :notes do
    member do
      put 'unshare'
    end
  end
  
  root to: 'home#about'
  
  get 'home/index'
  get '/dashboard' => 'dashboard#show'
  get 'shared_notes/:id' => 'shared_notes#show'
  
  post '/notes/process/' => 'notes#process_markdown'
  
  get '/trash' => 'trash#show'
  
  resources :trashed_notes, only: [:index, :update, :destroy]
  
  post '/trash' => 'trashed_notes#emptyTrash'

end

app/models/note.rb
class Note < ActiveRecord::Base
  require 'digest/sha1'
  belongs_to :user
  has_many :tags

  validates_length_of :title, maximum: 250
  validates_presence_of :title, :content
  
  acts_as_taggable

  def share
    self.slug = SecureRandom.urlsafe_base64
  end
  
  def unshare
    self.slug = nil
  end
  
  def self.find_all_by_query(query)
    query = query.downcase
    query = "%#{query}%"
    Note.where(['lower(title) like ?
                 OR lower(content) like ?',
                 query, query])
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :notes
  has_many :tags, through: :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def show
    @recent_notes = current_user.notes.order('updated_at DESC').limit(5)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end
    
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy, :share, :unshare]
  before_action :authenticate_user!, except: [:share]
  # GET /notes
  # GET /notes.json
  def index
    @trashed_notes = current_user.notes.where(:trash => true)
    if params[:q]
      @notes = current_user.notes.find_all_by_query(params[:q]).where(:trash => false)
      if @notes.empty?
        render "search/no_results"
      end
    else
      if current_user.notes.all.where(:trash => false) == []
        render "notes/no_notes"
      else
        @notes = current_user.notes.all.order('updated_at DESC').where(:trash => false)
      end
    end
  end
  
  def set_tags
    @tags = current_user.tags.collect{|t| t.name}.to_json
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to edit_note_path(@note), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to edit_note_path(@note), notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.trash = true
    @note.save
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully moved to trash.' }
      format.json { head :no_content }
    end
  end
  
  def process_markdown
    text_to_transform = params[:text]
    html = Kramdown::Document.new(text_to_transform).to_html
    render :text => html
  end
  
  def share
    @note.share
    @note.save
    redirect_to edit_note_path(@note), notice: 'Note was successfully shared.'
  end
  
  def unshare
    @note.unshare
    @note.save
    redirect_to edit_note_path(@note), notice: 'Note was successfully unshared.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :tag, :content, :tag_list)
    end
end

app/controllers/shared_notes_controller.rb
class SharedNotesController < ApplicationController
  
  def show
    slug = params[:id]
    @note = Note.find_by_slug(slug)
    if @note == nil
      render 'shared_notes/no_shared_notes'
    else
      render 'notes/edit'
    end
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def show
    @notes = current_user.notes.tagged_with(params[:tag]).where(:trash => false)
     render 'notes/index.html.erb'
  end
end

app/controllers/trash_controller.rb
class TrashController < ApplicationController
  before_action :authenticate_user!
  def show
    @trashed_notes = current_user.notes.where(:trash => true)
  end 
  
  def trash
    @note = current_user.notes.find(params[:note_id]).update(:trash => true)
    @note.save
  end

end

app/controllers/trashed_notes_controller.rb
class TrashedNotesController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  
  def update
    @note = Note.find(params[:id])
    @note.trash = false
    @note.save
    redirect_to trash_path, notice: "Note has been successfully restored."
  end
  
  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to trash_path, notice: "Note was permanently deleted."
  end
  
  def emptyTrash
    @trashed_notes = Note.where(:trash => true)
    @trashed_notes.destroy_all
    redirect_to(:back, notice: "Your trash is empty.")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autocomplete_helper.rb
module AutocompleteHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def kramdown(text)
    # if text is nil, or "", there's no reason to process.
    return "" if text.blank?   # blank is Rails' object shortcut for "nil or emptystring"
    Kramdown::Document.new(text).to_html.html_safe
  end
end

app/helpers/parser_helper.rb
module ParserHelper
end

app/helpers/shared_notes_helper.rb
module SharedNotesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/trash_helper.rb
module TrashHelper
end

app/helpers/trashed_notes_helper.rb
module TrashedNotesHelper
end

app/views/dashboard/show.html.erb
<h1>Dashboard</h1>

<table>
    <thead>
        <tr>
          <th>Recent Notes</th>
          <th>Last Updated</th>
        </tr>
    </thead>
  <tbody>
    <% @recent_notes.each do |note| %>
      <tr>
        <td><%= link_to note.title, edit_note_path(note), class: "title_link" %></td>
        <td><%= time_ago_in_words(note.updated_at) %> ago</td>
        <td><%= link_to image_tag("trashcan.png"), note, method: :delete, data: { confirm: 'Are you sure?' }, class: "trash" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Note', new_note_path, class: "btn" %>

app/views/home/about.html.erb
<h1 class="logo">Scrawl</h1>
<div class="text-center">
    <%= link_to 'Start Editing', {controller: 'notes', action: 'new'}, class: "btn" %>
</div>
<div id="screenshot">
  <img src="assets/screenshot.png">
</div>

app/views/home/index.html.erb
<h1>Editor</h1>

<div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scrawl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600,400italic,300,800' rel='stylesheet' type='text/css'>
</head>
<body>
  <div id="bluestripe">
    <% if user_signed_in? %>
      <div class="container">
        <%= render "/search/search" %>
      </div>
    <%end%>
  </div>
  <div class="container">
    <% if user_signed_in? %>
    <p class="signOut">Signed is as <%= current_user.email %>. Not you? 
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: 'link' %> </p>
        <nav>
          <% if @trashed_notes.nil? %>
          <p id="badge">0</p>
          <%else%>
          <p id="badge"><%= @trashed_notes.count%></p>
          <%end%>
          <%= link_to 'Trash', trash_path, class: 'link' %>
          <%= link_to 'Dashboard', dashboard_path, class: 'link' %>
          <%= link_to 'My Notes', notes_path, class: 'link' %>
        </nav>
      
    <div class="small_logo"></div>
    <% else %>
    <br><br>
      <%= link_to "Sign Up", new_user_registration_path, class: 'link' %> or <%= link_to "Sign In", new_user_session_path, class: 'link' %>
    <% end %> 
  </div>
  <div class="container">
    
    <div class="row">
    <% if notice %>
      <h4 id="notice" class="col-md-5"><%= notice %></h4>
    <% end %>
    </div>
    <% if alert %>
      <h4 class="alert"><%= alert %></h4>
    <% end %>
      <%= yield %>
    
  </div>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="field, col-md-6">
    <%= f.label :title %><%= content_tag :span, ' - limit of 250 characters' %><br>
    <%= f.text_field :title, :maxlength => 250, :placeholder  => 'e.g. Homework for BI class, Plan end of semester party', class:"col-md-12" %><br><br>
  </div>
  <div class="field, col-md-6">
    <%= f.label :tags %><%= content_tag :span, ' - separate tags with commas' %><br>
    <%= f.text_field :tag_list, value: @note.tag_list.to_s, :placeholder  => 'e.g. groceries, shopping, pet, party, clothes', class:"col-md-12" %><br><br>
  </div>

    <div class="field, col-md-6">
      <%= f.label :content %><%= content_tag :span, ' - type your note here using markdown' %>
        <%= f.text_area :content, :rows=>20, class:"col-md-12" %>
    </div>

    <div class="field, col-md-6">
      <%= f.label :preview %><%= content_tag :span, ' - see your markdown in action' %>
        <div id=preview>
          <%= kramdown(@note.content) %>
        </div>
    </div>
    
    </div>
   
<br>
  <div class="actions" >
    <%= f.submit "Save Note", class: "btn" %>
  </div>

<% end %>

<script>
  $(function() {
    var availableTags = <%= current_user.tags.collect{|t| t.name}.to_json.html_safe %>
      $("#note_tag_list").autocomplete({
        source: availableTags
      });
  });
</script>

app/views/notes/edit.html.erb
<h1>Editing Note "<%= @note.title %>"</h1>

<%= link_to 'My Notes', notes_path, class: "btn" %>
<%= link_to 'Share', share_note_path(@note), class: "btn", method: :put if @note.slug.blank? %>
<%= link_to 'Unshare', unshare_note_path(@note), class: "btn", method: :put if @note.slug.present? %>
<br><br>
<% if @note.slug.present? %>
  <p>
    <strong>Shareable URL: </strong><%= url_for :controller => "shared_notes", :action => "show", :id => @note.slug, :only_path => false %>
  </p>
<% end %>

<%= render 'form' %>
<%= link_to 'Create New Note', new_note_path, class: "btn" %>

app/views/notes/index.html.erb
<h1>My Notes</h1>

<%= link_to 'New Note', new_note_path, class: "btn" %>

<div id="tag_cloud">
  <h3>Filter by tag:</h3>
  <% tag_cloud current_user.notes.tag_counts, %w[d m l] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: "tag_link" %>
      <% end %>
</div><br>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Last Updated</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  

  <tbody>
    <% @notes.each do |note| %>
      <% if note.user == current_user %>
        <tr>
          <td><%= link_to note.title, edit_note_path(note), class: "title_link" %></td>
          <td><%= time_ago_in_words(note.updated_at) %> ago</td>
          <td><%= raw note.tag_list.map { |t| link_to t, tag_path(t), class: "tag_link" }.join(' ') %></td>
          <td><%= link_to image_tag("trashcan.png"), note, method: :delete, data: { confirm: 'Move this note to the trash?' }, class: "trash" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

app/views/notes/no_notes.html.erb
<h3>You don't have any saved notes.</h3>
<h4>To get started, create a <%= link_to 'New Note', new_note_path, class: "btn" %></h4>

app/views/notes/show.html.erb
<% if @note.user == current_user %>
<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @note.tag %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<% if @note.slug.present? %>
  <p>
    <strong>Shareable URL: </strong><%= url_for :controller => "shared_notes", :action => "show", :id => @note.slug, :only_path => false %>
  </p>
<% end %>

<%= link_to 'Edit', edit_note_path(@note), class: "btn" %>
<%= link_to 'Back', notes_path, class: "btn" %>
<% end %>

app/views/search/_search.html.erb
<%= form_tag notes_url, id: "search", method: :get do %>
  <label for="query">Search: </label>
  <input type="search" id="query" name="q" value="<%= params[:q] %>">
  <input type="submit" value="Search" class="link">
<% end %>

app/views/search/no_results.html.erb
<h3>Your search did not return any notes.  Please try again.</h3>

app/views/shared_notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="field, col-md-6">
    <%= f.label :title %><%= content_tag :span, ' - limit of 250 characters' %><br>
    <%= f.text_field :title, :maxlength => 250, :placeholder  => 'e.g. Homework for BI class, Plan end of semester party', class:"col-md-12" %><br><br>
  </div>
  <div class="field, col-md-6">
    <%= f.label :tags %><%= content_tag :span, ' - separate tags with commas' %><br>
    <%= f.text_field :tag_list, value: @note.tag_list.to_s, :placeholder  => 'e.g. groceries, shopping, pet, party, clothes', class:"col-md-12" %><br><br>
  </div>

    <div class="field, col-md-6">
      <%= f.label :content %><%= content_tag :span, ' - type your note here using markdown' %>
        <%= f.text_area :content, :rows=>20, class:"col-md-12" %>
    </div>

    <div class="field, col-md-6">
      <%= f.label :preview %><%= content_tag :span, ' - see your markdown in action' %>
        <div id=preview>
          <%= kramdown(@note.content) %>
        </div>
    </div>
    
    </div>
   
<br>
  <div class="actions" >
    <%= f.submit "Save Note", class: "btn" %>
  </div>

<% end %>

app/views/shared_notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= link_to note.title, edit_note_path(note), class: "link" %></td>
        <td><%= note.tag %></td>
        <td><%= link_to 'Edit', edit_note_path(note) class: "link"%></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }, class: "link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path, class: "link" %>

app/views/shared_notes/no_shared_notes.html.erb
<h3>This note is no longer being shared.</h3>
<%= link_to 'My Notes', notes_path, class: "btn" %>

app/views/shared_notes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @note.tag %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/trash/show.html.erb
<h1>Trash</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Last Updated</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <% if @trashed_notes.empty? %>
      <p>Your trash is empty.</p>
    <%end%>


  <tbody>
    <% @trashed_notes.each do |note| %>
      <tr>
        <td><%= link_to note.title, edit_note_path(note), class: "title_link" %></td>
        <td><%= time_ago_in_words(note.updated_at) %></td>
        <td><%= raw note.tag_list.map { |t| link_to t, tag_path(t), class: "tag_link" }.join(' ') %></td>
        <td><%= button_to "Restore", trashed_note_path(note), :method => :patch, class: "btn" %> </td>
        <td><%= button_to 'Delete', trashed_note_path(note), :method => :delete, data: { confirm: 'Are you sure you want to permanently delete this note?' }, class: "btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_to 'Empty Trash', :method => :emptyTrash, class: "btn", data: { confirm: 'Empty trash?'} %>